### ISSUE TITLE
Installing with NPM is broken

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [andreruffert/rangeslider.js#293]
When I try to install range slider from NPM using default command
npm install --save rangeslider.js
I get this error
`
5876 verbose stack TypeError: Cannot read property '0' of undefined
5876 verbose stack     at rmStuff (C:\Program Files\nodejs\node_modules\npm\lib\unbuild.js:61:24)
5876 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
5876 verbose stack     at ret (eval at makeNodePromisifiedEval (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
5876 verbose stack     at lifecycle.then.then (C:\Program Files\nodejs\node_modules\npm\lib\install\action\unbuild.js:12:12)
5876 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
5876 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
5876 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
5876 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
5876 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
5876 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
5876 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
5876 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
5876 verbose stack     at runCallback (timers.js:781:20)
5876 verbose stack     at tryOnImmediate (timers.js:743:5)
5876 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
`
attaching the full error log below
[2017-12-12T16_47_48_265Z-debug.log](https://github.com/andreruffert/rangeslider.js/files/1552529/2017-12-12T16_47_48_265Z-debug.log)

**Comment by igolka97** [comment]
any news about this?
